INSERT INTO 'users'('id','username','password','role') VALUES ("1","AdamG","Hello1","admin");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap1","51.588969", "-3.00137", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap2","51.5877", "-2.99835", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap3","51.5877", "-2.99735", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap4","51", "-3.00137", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap5","51.5877", "-2", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap6","51.5877", "-2.5", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap7","51.5", "-3.00137", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap8","5.5877", "-2.935", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap9","5.5", "-2.35", "1",date(julianday('now')),"Temporary Description");
INSERT INTO 'taps'('address','latitude','longitude', 'userID','postDate', 'description') VALUES ("Tap10","5", "-2.5", "1",date(julianday('now')),"Temporary Description");
